# Generated by Django 2.0.5 on 2018-05-22 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='massage',
            new_name='message',
        ),
    ]
